server:
  port: ${PORT:8080}

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: book_finder

  datasource:
    # Priority: Railway Variable -> Local Docker -> Local H2 (if needed)
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bf_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS:86400000}

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}