CREATE TABLE users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_banned  BOOLEAN      NOT NULL,
    join_date  DATE         NOT NULL,
    bio        VARCHAR(1600),
    email      VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    password   VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uq_roles_role_name UNIQUE (role_name),
    CONSTRAINT chk_roles_role_name CHECK (role_name IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE series
(
    series_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    publish_date DATE         NOT NULL,
    user_id      BIGINT       NOT NULL,
    description  VARCHAR(1600),
    series_name  VARCHAR(255) NOT NULL,

    CONSTRAINT pk_series PRIMARY KEY (series_id),
    CONSTRAINT fk_series_user FOREIGN KEY (user_id)
        REFERENCES users (user_id)
);

CREATE TABLE genres
(
    genre_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    genre_name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_genres PRIMARY KEY (genre_id),
    CONSTRAINT uq_genres_genre_name UNIQUE (genre_name)
);

CREATE TABLE hashtags
(
    hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    hashtag    VARCHAR(255) NOT NULL,

    CONSTRAINT pk_hashtags PRIMARY KEY (hashtag_id),
    CONSTRAINT uq_hashtags_hashtag UNIQUE (hashtag)
);

CREATE TABLE books
(
    book_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    publish_date  DATE         NOT NULL,
    volume_number INTEGER,
    series_id     BIGINT,
    user_id       BIGINT       NOT NULL,
    summary       VARCHAR(2400),
    title         VARCHAR(255) NOT NULL,

    CONSTRAINT pk_books PRIMARY KEY (book_id),
    CONSTRAINT uq_books_series_volume UNIQUE (series_id, volume_number),

    CONSTRAINT fk_books_series FOREIGN KEY (series_id)
        REFERENCES series (series_id),

    CONSTRAINT fk_books_user FOREIGN KEY (user_id)
        REFERENCES users (user_id)
);

CREATE TABLE chapters
(
    chapter_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    chapter_number INTEGER      NOT NULL,
    book_id        BIGINT       NOT NULL,
    content_type   VARCHAR(255) NOT NULL,
    s3_key         VARCHAR(255) NOT NULL,
    title          VARCHAR(255) NOT NULL,

    CONSTRAINT pk_chapters PRIMARY KEY (chapter_id),

    CONSTRAINT uq_chapters_book_chapter UNIQUE (book_id, chapter_number),

    CONSTRAINT chk_chapters_content_type
        CHECK (content_type IN ('MARKDOWN', 'HTML')),

    CONSTRAINT fk_chapters_book FOREIGN KEY (book_id)
        REFERENCES books (book_id)
);

CREATE TABLE reviews
(
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rating    INTEGER NOT NULL,
    book_id   BIGINT  NOT NULL,
    user_id   BIGINT  NOT NULL,
    comment   VARCHAR(2000),

    CONSTRAINT pk_reviews PRIMARY KEY (review_id),

    CONSTRAINT uq_reviews_user_book UNIQUE (user_id, book_id),

    CONSTRAINT chk_reviews_rating CHECK (rating >= 1 AND rating <= 5),

    CONSTRAINT fk_reviews_book FOREIGN KEY (book_id)
        REFERENCES books (book_id),

    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id)
        REFERENCES users (user_id)
);

CREATE TABLE book_genres
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,

    CONSTRAINT pk_book_genres PRIMARY KEY (book_id, genre_id),

    CONSTRAINT fk_book_genres_book FOREIGN KEY (book_id)
        REFERENCES books (book_id),

    CONSTRAINT fk_book_genres_genre FOREIGN KEY (genre_id)
        REFERENCES genres (genre_id)
);

CREATE TABLE book_hashtags
(
    book_id    BIGINT NOT NULL,
    hashtag_id BIGINT NOT NULL,

    CONSTRAINT pk_book_hashtags PRIMARY KEY (book_id, hashtag_id),

    CONSTRAINT fk_book_hashtags_book FOREIGN KEY (book_id)
        REFERENCES books (book_id),

    CONSTRAINT fk_book_hashtags_hashtag FOREIGN KEY (hashtag_id)
        REFERENCES hashtags (hashtag_id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),

    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
);