INSERT INTO genres (genre_name)
VALUES ('Fantasy'),
       ('Science Fiction'),
       ('Mystery'),
       ('Romance'),
       ('Thriller'),
       ('Horror'),
       ('Adventure'),
       ('Historical Fiction'),
       ('Young Adult'),
       ('Dystopian'),
       ('Urban Fantasy'),
       ('Paranormal'),
       ('Crime'),
       ('Drama'),
       ('Action'),
       ('Literary Fiction'),
       ('Dark Fantasy'),
       ('Biography'),
       ('Space Opera'),
       ('Steampunk'),
       ('Cyberpunk'),
       ('Magical Realism'),
       ('Supernatural'),
       ('Suspense'),
       ('Contemporary Fiction') ON CONFLICT DO NOTHING;